export const CATEGORY_RULES = {
  Groceries: [
    "costco",
    "safeway",
    "kroger",
    "ralphs",
    "whole foods",
    "walmart grocery",
    "trader joe's",
    "aldi",
    "publix",
    "wegmans",
    "heb",
    "fred meyer",
    "stop & shop",
    "giant food",
    "shoppers",
    "sam's club",
    "bj's wholesale",
    "sprouts",
    "fresh market",
    "winco"
  ],
  Dining: [
    "cheesecake factory",
    "olive garden",
    "applebee's",
    "chili's",
    "buffalo wild wings",
    "pf chang's",
    "red robin",
    "outback steakhouse",
    "maggiano's",
    "cracker barrel",
    "fogo de chao",
    "tgi friday's",
    "longhorn steakhouse",
    "yard house",
    "mellow mushroom",
    "ruby tuesday",
    "benihana",
    "williamsburg pizza",
    "shake shack",
    "sweetgreen"
  ],
  Fast_Food: [
    "mcdonald's",
    "burger king",
    "wendy's",
    "taco bell",
    "chipotle",
    "kfc",
    "popeyes",
    "chick-fil-a",
    "five guys",
    "jack in the box",
    "arby's",
    "little caesars",
    "domino's",
    "papa john's",
    "subway",
    "jimmy john's",
    "panera",
    "raising cane's",
    "in-n-out",
    "culver's"
  ],
  Coffee: [
    "starbucks",
    "dunkin",
    "dutch bros",
    "peet's coffee",
    "tim hortons",
    "philz coffee",
    "caribou coffee",
    "blue bottle coffee",
    "pret a manger",
    "coffee bean",
    "gloria jean's",
    "intelligentsia",
    "joe coffee",
    "lavazza",
    "nero",
    "ennis coffee",
    "aroma coffee",
    "stumptown coffee",
    "gregorys coffee",
    "verve coffee"
  ],
  Gas: [
    "shell",
    "chevron",
    "bp",
    "exxon",
    "mobil",
    "valero",
    "sunoco",
    "citgo",
    "pilot",
    "flying j",
    "costco fuel",
    "safeway fuel",
    "wawa fuel",
    "love's travel stop",
    "speedway",
    "circle k",
    "quiktrip",
    "casey's",
    "kum & go"
  ],
  Transportation: [
    "metrocard",
    "mta",
    "bart",
    "cta",
    "rideau transit",
    "sound transit",
    "septa",
    "dart",
    "mart",
    "pace bus",
    "greyhound",
    "amtrak",
    "megabus",
    "boltbus",
    "via rail",
    "flixbus",
    "brightline",
    "nj transit",
    "miami dade transit",
    "vta"
  ],
  Rides: [
    "uber",
    "lyft",
    "uber eats",
    "doordash",
    "postmates",
    "grubhub",
    "instacart",
    "getaround",
    "turo",
    "lime",
    "bird",
    "spin",
    "revel",
    "bla bla car",
    "caviar",
    "favor",
    "gojek",
    "careem",
    "ola",
    "didi"
  ],
  Utilities: [
    "pg&e",
    "coned",
    "duke energy",
    "southern california edison",
    "georgia power",
    "laclede gas",
    "national grid",
    "xcel energy",
    "dominion energy",
    "smud",
    "we energies",
    "pse&g",
    "pepco",
    "evergy",
    "srp",
    "fpl",
    "bge",
    "spire energy",
    "midamerican energy",
    "nv energy"
  ],
  Internet: [
    "comcast",
    "xfinity",
    "spectrum",
    "cox communications",
    "verizon",
    "at&t",
    "t-mobile",
    "cricket wireless",
    "mint mobile",
    "google fi",
    "boost mobile",
    "visible",
    "frontier",
    "optimum",
    "wow internet",
    "centurylink",
    "earthlink",
    "rcn",
    "hulu live",
    "sling tv"
  ],
  Streaming: [
    "netflix",
    "hulu",
    "disney+",
    "spotify",
    "apple music",
    "apple tv",
    "amazon prime video",
    "hbomax",
    "paramount+",
    "peacock",
    "youtube premium",
    "pandora",
    "audible",
    "crunchyroll",
    "scribd",
    "twitch",
    "siriusxm",
    "iheartradio",
    "showtime",
    "starz"
  ],
  Insurance: [
    "geico",
    "state farm",
    "progressive",
    "allstate",
    "nationwide",
    "liberty mutual",
    "esurance",
    "farmers insurance",
    "usaa",
    "aaa",
    "metlife",
    "travelers",
    "the hartford",
    "amica",
    "ajg insurance",
    "oscar health",
    "lemonade insurance",
    "root insurance",
    "kemper",
    "assurant"
  ],
  Healthcare: [
    "kaiser permanente",
    "sutter health",
    "cvs health",
    "walgreens health",
    "rite aid pharmacy",
    "quest diagnostics",
    "labcorp",
    "planned parenthood",
    "dignity health",
    "cleveland clinic",
    "mayo clinic",
    "nyu langone",
    "banner health",
    "hca healthcare",
    "commonspirit health",
    "onedental",
    "zocdoc",
    "capsule pharmacy",
    "pillpack",
    "healthfirst"
  ],
  Pharmacy: [
    "cvs",
    "walgreens",
    "rite aid",
    "duane reade",
    "boots pharmacy",
    "superdrug pharmacy",
    "london drugs",
    "shoppers drug mart",
    "costco pharmacy",
    "walmart pharmacy",
    "kroger pharmacy",
    "heb pharmacy",
    "meijer pharmacy",
    "publix pharmacy",
    "safeway pharmacy",
    "fred meyer pharmacy",
    "brookshire pharmacy",
    "giant eagle pharmacy",
    "hy-vee pharmacy",
    "longs drugs"
  ],
  Fitness: [
    "planet fitness",
    "24 hour fitness",
    "la fitness",
    "equinox",
    "orange theory",
    "anytime fitness",
    "snap fitness",
    "crunch fitness",
    "ymca",
    "soulcycle",
    "peloton",
    "classpass",
    "blink fitness",
    "lifetime fitness",
    "f45",
    "pure barre",
    "barrys bootcamp",
    "corepower yoga",
    "club pilates",
    "solidcore"
  ],
  Home_Improvement: [
    "home depot",
    "lowe's",
    "ace hardware",
    "menards",
    "true value",
    "harbor freight",
    "tractor supply",
    "floor & decor",
    "sherwin-williams",
    "ferguson",
    "build.com",
    "ikea",
    "wayfair",
    "overstock",
    "restoration hardware",
    "crate & barrel",
    "west elm",
    "cb2",
    "pottery barn",
    "room & board"
  ],
  Electronics: [
    "best buy",
    "micro center",
    "fry's electronics",
    "newegg",
    "b&h photo",
    "adorama",
    "gamestop",
    "apple store",
    "microsoft store",
    "google store",
    "razer",
    "dell",
    "hp store",
    "lenovo store",
    "samsung store",
    "logitech",
    "sonos",
    "staples",
    "office depot",
    "office max"
  ],
  Online_Shopping: [
    "amazon",
    "amazon marketplace",
    "ebay",
    "etsy",
    "wish",
    "aliexpress",
    "temu",
    "shein",
    "zalando",
    "asos",
    "farfetch",
    "zappos",
    "shopify",
    "big cartel",
    "mercari",
    "poshmark",
    "stockx",
    "goat",
    "backcountry",
    "massdrop"
  ],
  Travel: [
    "expedia",
    "orbitz",
    "priceline",
    "kayak",
    "travelocity",
    "booking.com",
    "agoda",
    "airbnb",
    "vrbo",
    "hopper",
    "skyscanner",
    "trip.com",
    "cheapcaribbean",
    "hotwire",
    "hoteltonight",
    "travala",
    "google travel",
    "amex travel",
    "chase travel",
    "delta vacations"
  ],
  Lodging: [
    "marriott",
    "hilton",
    "hyatt",
    "ihg",
    "best western",
    "choice hotels",
    "wyndham",
    "four seasons",
    "ritz-carlton",
    "fairmont",
    "accor",
    "omni hotels",
    "kimpton",
    "drury inn",
    "motel 6",
    "red roof inn",
    "la quinta",
    "embassy suites",
    "aloft hotels",
    "doubletree"
  ],
  Airlines: [
    "delta",
    "american airlines",
    "united airlines",
    "southwest",
    "jetblue",
    "alaska airlines",
    "frontier",
    "spirit airlines",
    "sun country",
    "hawaiian airlines",
    "british airways",
    "air canada",
    "lufthansa",
    "air france",
    "klm",
    "emirates",
    "qatar airways",
    "singapore airlines",
    "virgin atlantic",
    "ryanair"
  ],
  Car_Rental: [
    "enterprise",
    "hertz",
    "avis",
    "budget car rental",
    "alamo",
    "national car rental",
    "thrifty",
    "dollar car rental",
    "sixt",
    "fox rent a car",
    "payless car",
    "zipcar",
    "getaround rentals",
    "turo rentals",
    "rentcars",
    "easirent",
    "easirent uk",
    "europcar",
    "ace rent a car",
    "nucarrentals"
  ],
  Entertainment: [
    "amc theatres",
    "regal cinemas",
    "cinemark",
    "alamo drafthouse",
    "fandango",
    "ticketmaster",
    "stubhub",
    "axs tickets",
    "live nation",
    "draftkings",
    "fanduel",
    "topgolf",
    "main event",
    "bowlero",
    "dave & buster's",
    "pinstripes",
    "escape the room",
    "museum of modern art",
    "disneyland",
    "six flags"
  ],
  Kids: [
    "buybuy baby",
    "babies r us",
    "the children's place",
    "carter's",
    "oshkosh",
    "gymboree",
    "littlespoon",
    "hanna andersson",
    "pottery barn kids",
    "fat brain toys",
    "lovevery",
    "target baby",
    "johnson's baby",
    "honest company",
    "babylist",
    "bugaboo",
    "uppababy",
    "pampers",
    "similac",
    "gerber"
  ],
  Pets: [
    "petsmart",
    "petco",
    "chewy",
    "barkbox",
    "pet supplies plus",
    "pet supermarket",
    "petland",
    "pet food express",
    "pet valu",
    "pet sense",
    "blue buffalo",
    "maddies pet",
    "tails.com",
    "nomnom",
    "ollie pet",
    "freshpet",
    "whistle",
    "pet first aid",
    "vetco",
    "banfield"
  ],
  Clothing: [
    "nike",
    "adidas",
    "lululemon",
    "under armour",
    "gap",
    "old navy",
    "banana republic",
    "j crew",
    "uniqlo",
    "zara",
    "hm",
    "forever 21",
    "urban outfitters",
    "anthropologie",
    "express",
    "abercrombie",
    "hollister",
    "madewell",
    "free people",
    "patagonia"
  ],
  Personal_Care: [
    "sephora",
    "ulta",
    "bath & body works",
    "lush cosmetics",
    "sally beauty",
    "glossier",
    "ipsy",
    "fenty beauty",
    "mac cosmetics",
    "clinique",
    "kiel's",
    "the body shop",
    "bluemercury",
    "birchbox",
    "function of beauty",
    "everlane beauty",
    "rituals cosmetics",
    "walgreens beauty",
    "boots beauty",
    "drunk elephant"
  ],
  Education: [
    "udemy",
    "coursera",
    "edx",
    "skillshare",
    "lynda",
    "khan academy",
    "treehouse",
    "pluralsight",
    "general assembly",
    "codecademy",
    "duolingo",
    "babbel",
    "rosedale tech",
    "brainpop",
    "mcgraw hill",
    "pearson education",
    "chegg",
    "quizlet",
    "varsity tutors",
    "masterclass"
  ],
  Software: [
    "adobe",
    "microsoft 365",
    "dropbox",
    "evernote",
    "notion",
    "slack",
    "zoom",
    "github",
    "atlassian",
    "asana",
    "trello",
    "canva",
    "figma",
    "autodesk",
    "salesforce",
    "shopify subscription",
    "quickbooks",
    "freshbooks",
    "intuit",
    "xero"
  ],
  Financial_Services: [
    "paypal",
    "venmo",
    "cash app",
    "stripe",
    "square",
    "robinhood",
    "coinbase",
    "binance",
    "chime",
    "sofi",
    "ally",
    "charles schwab",
    "fidelity",
    "vanguard",
    "etrade",
    "td ameritrade",
    "wealthfront",
    "betterment",
    "mint",
    "ynab"
  ],
  Charity: [
    "red cross",
    "unicef",
    "doctors without borders",
    "world vision",
    "save the children",
    "feed the children",
    "st jude",
    "rotary foundation",
    "direct relief",
    "oxfam",
    "charity water",
    "world wildlife fund",
    "nature conservancy",
    "planned parenthood donation",
    "sierra club",
    "habitat for humanity",
    "united way",
    "greenpeace",
    "wounded warrior project",
    "american cancer society"
  ]
};

export const COLORS = [
  "#0f4c81",
  "#1f77b4",
  "#2a9d8f",
  "#264653",
  "#e76f51",
  "#f4a261",
  "#e9c46a",
  "#2c7da0",
  "#76c893",
  "#f3722c",
  "#f8961e",
  "#f9844a",
  "#f9c74f",
  "#90be6d",
  "#43aa8b",
  "#577590",
  "#277da1",
  "#4d908e",
  "#4895ef",
  "#4361ee",
  "#3a0ca3",
  "#7209b7",
  "#b5179e",
  "#f72585",
  "#ff6f91",
  "#ff9a8b",
  "#f28482",
  "#e5989b",
  "#b5838d",
  "#6d597a",
  "#355070",
  "#4472ca",
  "#00b4d8",
  "#48cae4",
  "#ade8f4",
  "#023e8a",
  "#03045e",
  "#006d77",
  "#83c5be",
  "#edf6f9",
  "#0d3b66",
  "#faa307",
  "#ffd166",
  "#06d6a0",
  "#118ab2",
  "#ef476f",
  "#073b4c",
  "#6bc8a4",
  "#c1d7ae",
  "#f7b267"
];
